### ISSUE TITLE
Gostaria de saber se faz pagamento a debito

### ISSUE THREAD

**Issue by DavidGina306** [jlcd/api-cielo30#1]
Como faço para utilizar o pagamento a debito....

**Comment by jlcd** [comment]
Pagamento via débito não foi implementado.


Os métodos atualmente desenvolvidos são:

> `payment`: Realiza pagamento (apenas via Cartão de Crédito ou token de Cartão de Crédito)
> `cancelPayment`: Cancelamento de pagamento já realizado
> `capturePayment`: Captura de pagamento já realizado
> `tokenizeCreditCard`: Tokenização de Cartão
